[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run start"
  targetPort = 3000
  port = 8888
  framework = "#custom"
  publish = "apps/landing"

[[edge_functions]]
  path = "/socket"
  function = "socket"
